CREATE TABLE IF NOT EXISTS questions(
	id INT(10) AUTO_INCREMENT,
	code VARCHAR(32) NOT NULL,
	content VARCHAR(512) DEFAULT NULL,
	user_id INT DEFAULT 0 NOT NULL,
	posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS comments(
	id INT(10) AUTO_INCREMENT,
	question_id INT(10),
	content VARCHAR(512) DEFAULT NULL,
	user_id INT DEFAULT 0 NOT NULL,
	posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS users(
	id INT(10) AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY(id)
);